= Cloud

== Connecting

To connect to a DataStax Astra cluster:

. Download the secure connect bundle from your Astra account.
. Connect to your cluster with

[source,python]
----
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider

cloud_config = {
    'secure_connect_bundle': '/path/to/secure-connect-dbname.zip'
}
auth_provider = PlainTextAuthProvider(username='user', password='pass')
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()
----

== Cloud Config Options

=== use_default_tempdir

The secure connect bundle needs to be extracted to load the certificates into the SSLContext.
By default, the zip location is used as the base dir for the extraction.
In some environments, the zip location file system is read-only (e.g Azure Function).
With _use_default_tempdir_ set to _True_, the default temporary directory of the system will be used as base dir.

[source,python]
----
cloud_config = {
      'secure_connect_bundle': '/path/to/secure-connect-dbname.zip',
      'use_default_tempdir': True
}
...
----

== Astra Differences

In most circumstances, the client code for interacting with an Astra cluster will be the same as interacting with any other Cassandra cluster.
The exceptions being:

* A cloud configuration must be passed to a `~.Cluster`{.interpreted-text role="class"} instance via the [cloud]{.title-ref} attribute (as demonstrated above).
* An SSL connection will be established automatically.
Manual SSL configuration is not allowed, and using [ssl_context]{.title-ref} or [ssl_options]{.title-ref} will result in an exception.
* A `~.Cluster`{.interpreted-text role="class"}'s [contact_points]{.title-ref} attribute should not be used.
The cloud config contains all of the necessary contact information.
* If a consistency level is not specified for an execution profile or query, then `.ConsistencyLevel.LOCAL_QUORUM`{.interpreted-text role="attr"} will be used as the default.

== Limitations

[discrete]
==== Event loops

Evenlet isn't yet supported for python 3.7+ due to an https://github.com/eventlet/eventlet/issues/526[issue in Eventlet].

== CqlEngine

When using the object mapper, you can configure cqlengine with `~.cqlengine.connection.set_session`{.interpreted-text role="func"}:

[source,python]
----
from cassandra.cqlengine import connection
...

c = Cluster(cloud={'secure_connect_bundle':'/path/to/secure-connect-test.zip'},
            auth_provider=PlainTextAuthProvider('user', 'pass'))
s = c.connect('myastrakeyspace')
connection.set_session(s)
...
----

If you are using some third-party libraries (flask, django, etc.), you might not be able to change the configuration mechanism.
For this reason, the [hosts]{.title-ref} argument of the default `~.cqlengine.connection.setup`{.interpreted-text role="func"} function will be ignored if a [cloud]{.title-ref} config is provided:

[source,python]
----
from cassandra.cqlengine import connection
...

connection.setup(
  None,  # or anything else
  "myastrakeyspace", cloud={
    'secure_connect_bundle':'/path/to/secure-connect-test.zip'
  },
  auth_provider=PlainTextAuthProvider('user', 'pass'))
----
