name: Build MacOS
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      JOBS: 4
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
    steps:

    - name: Checkout
      uses: actions/checkout@v4
