name: Build MacOS
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Packages (macOS)
      if: matrix.os == 'macos-14'
      run: brew install libev

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Python Version
      run: python --version

    - name: Build
      run: |
        pip install wheel
        python setup.py bdist_wheel

    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: Wheels (${{ matrix.os }})
        path: ./dist/*.whl
