name: Build MacOS
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Python Version
      run: python --version

    - name: Build
      run: |
        pip install wheel
        python setup.py bdist_wheel
