name: Build Linux
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Packages
      run: |
        sudo apt-get update
        sudo apt-get install build-essential python-dev-is-python3 libev4 libev-dev

    - name: Python Version
      run: python --version

    - name: Build
      run: |
        pip install wheel
        python setup.py bdist_wheel

    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: Wheels (${{ matrix.os }})
        path: ./dist/*.whl
