name: Build MacOS
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Packages ARM64
      run: brew install libev

    - name: Packages X64
      run: |
        arch -x86_64 zsh
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        /usr/local/bin/brew install libev
  
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Python Version
      run: python --version

    - name: Build
      run: |
        pip install wheel
        python setup.py bdist_wheel

    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: Wheels (${{ matrix.os }})
        path: ./dist/*.whl
